### ISSUE TITLE
testnet brs 3.0 couple problems

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#349]
Local wallet version: https://github.com/burst-apps-team/burstcoin/commit/6a5c7d9d8706eb3dd0a4a6792820b3c8c344999f

My local config:
```
# Please change the following 2 lines!
P2P.myAddress=
P2P.myPlatform=local

DEV.API.Port = 6876
# This is a new port; please expose it.
DEV.API.V2.Port = 6878

DEV.TestNet = yes
DEV.Offline = no

DEV.P2P.BootstrapPeers = wallet.testnet.burst.devtrue.net;
# aya.onthewifi.com; fitzybits.mynetgear.com; test-burst.megash.it; 52.65.42.199; 75.100.126.230; testnet.getburst.net; tordek.mine.nu
DEV.P2P.rebroadcastTo = wallet.testnet.burst.devtrue.net;
P2P.NumBootstrapConnections = 1

P2P.savePeers=true
P2P.usePeersDb=true
P2P.getMorePeers=true

DEV.digitalGoodsStore.startBlock = 0
DEV.automatedTransactions.startBlock = 0
DEV.atFixBlock2.startBlock = 0
DEV.atFixBlock3.startBlock = 0
DEV.atFixBlock4.startBlock = 0
DEV.preDymaxion.startBlock = 0
DEV.poc2.startBlock = 0
DEV.rewardRecipient.startBlock = 6500

#### API SERVER ####
API.Listen = 0.0.0.0
API.allowed = *

P2P.shareMyAddress = yes
P2P.UPnP = no

#### DATABASE ####

# Database connection JDBC url
DEV.DB.Url=jdbc:sqlite:burst.sqlite
DEV.DB.Username=
DEV.DB.Password=
```

Wallet version wallet.testnet.burst.devtrue.net; : 3.0.0-alpha5

All cases, questions with one config above.

1.  I set only one peer with 3.0.0-alpha5, no sync , only after the lapse of ~3 min I was seen other peers in wallet and sync started to work.

DEV.P2P.BootstrapPeers = wallet.testnet.burst.devtrue.net;
DEV.P2P.rebroadcastTo = wallet.testnet.burst.devtrue.net;
P2P.NumBootstrapConnections = 1

Why so long time? Probably sync between last 3.0.0 versions doesn't work properly.

2. 
![image](https://user-images.githubusercontent.com/5445357/75525577-ac1acb80-5a42-11ea-8f68-83e71394cda1.png)

Now sync in progress, I see other peers.

```
$ sqlite3 burst.sqlite
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> select count(*) from block;
10486
sqlite> select count(*) from peer;
0
sqlite> 
```

peer table is empty, is it ok?

3. I can't select from transaction table....currently I can't understand why... I've checked other tables - I can interact with them.

```
$ sqlite3 burst.sqlite
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> .tables
account                   bid_order                 purchase_feedback       
account_asset             block                     purchase_public_feedback
alias                     escrow                    reward_recip_assign     
alias_offer               escrow_decision           subscription            
ask_order                 flyway_schema_history     trade                   
asset                     goods                     transaction             
asset_transfer            indirect_incoming         unconfirmed_transaction 
at                        peer                    
at_state                  purchase        
        
sqlite> .schema transaction
CREATE TABLE IF NOT EXISTS "transaction" (db_id INTEGER PRIMARY KEY AUTOINCREMENT, id BIGINT NOT NULL,
    deadline SMALLINT NOT NULL, sender_public_key BLOB NOT NULL, recipient_id BIGINT NULL,
    amount BIGINT NOT NULL, fee BIGINT NOT NULL,
    height INT NOT NULL, block_id BIGINT NOT NULL REFERENCES block (id) ON DELETE CASCADE,
    signature BLOB NULL, timestamp INT NOT NULL, type TINYINT NOT NULL, subtype TINYINT NOT NULL,
    sender_id BIGINT NOT NULL, attachment_bytes BLOB, block_timestamp INT NOT NULL, full_hash BLOB NOT NULL,
    referenced_transaction_fullhash BLOB, version TINYINT NOT NULL, has_message BOOLEAN NOT NULL DEFAULT FALSE,
    has_encrypted_message BOOLEAN NOT NULL DEFAULT FALSE, has_public_key_announcement BOOLEAN NOT NULL DEFAULT FALSE,
    ec_block_height INT DEFAULT NULL, ec_block_id BIGINT DEFAULT NULL, has_encrypttoself_message BOOLEAN NOT NULL DEFAULT FALSE);
CREATE UNIQUE INDEX transaction_id_idx ON "transaction" (id);
CREATE INDEX transaction_sender_id_idx ON "transaction" (sender_id);
CREATE UNIQUE INDEX transaction_full_hash_idx ON "transaction" (full_hash);
CREATE INDEX transaction_recipient_id_idx ON "transaction" (recipient_id);
CREATE INDEX transaction_block_timestamp_idx ON "transaction" (block_timestamp DESC);
CREATE INDEX transaction_recipient_id_amount_height_idx ON "transaction" (recipient_id, amount, height);

sqlite> select count(*) from transaction;
Error: near "transaction": syntax error
```

**Comment by llybin** [comment]
1. I forgot add in local config DEV.P2P.V2.Port = 7120 after that, sync starts instantly, Finished connecting to 1 well known peers. SOLVED

**Comment by llybin** [comment]
3. sqlite> select count(*) from "transaction";
9351
transaction is a [SQLite keyword](https://www.sqlite.org/lang_keywords.html) SOLVED

2. actual question

**Comment by harry1453** [comment]
hm, strange it isn't storing any, I will take a look

**Comment by llybin** [comment]
now new error... peer still empty
```
[WARNING] 2020-03-02 13:26:25 brs.peer.HttpPeerImpl - Error getting peers from peer
java.lang.Exception: Peer Error: java.lang.IllegalStateException: Could not find peer's address
        at brs.peer.HttpPeerImpl.checkError(HttpPeerImpl.kt:185)
        at brs.peer.HttpPeerImpl.getPeers(HttpPeerImpl.kt:303)
        at brs.services.impl.PeerServiceImpl$getMorePeersThread$1.invoke(PeerServiceImpl.kt:395)
        at brs.services.impl.PeerServiceImpl$getMorePeersThread$1.invoke(PeerServiceImpl.kt:47)
        at brs.services.impl.RxJavaTaskSchedulerService$repeatingTaskToTask$$inlined$safeCreateCompletable$1.subscribe(RxJavaTaskSchedulerService.kt:177)
        at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by harry1453** [comment]
That error was actually caused by my peer contacting yours on a different network, something about the remoteAddr caused it to fail.

I've identified what is preventing saving peers, I'll take a look at it
