### ISSUE TITLE
3.0 silent errors on start

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#352]
Enable DEBUG logging level:

```
# Default logging level (OFF, FINE, INFO, WARNING, SEVERE)
.level = FINE
```

`java -jar ./build/libs/burstcoin-all.jar`

```
[FINE] 2020-03-01 17:37:05 io.grpc.internal.AbstractServerImplBuilder - Unable to apply census tracing
java.lang.ClassNotFoundException: io.grpc.census.InternalCensusTracingAccessor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.grpc.internal.AbstractServerImplBuilder.getTracerFactories(AbstractServerImplBuilder.java:268)
        at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:227)
        at brs.api.grpc.api.ApiService.start(ApiService.kt:90)
        at brs.Burst$4.invoke(Burst.kt:134)
        at brs.Burst$4.invoke(Burst.kt:30)
        at brs.services.impl.RxJavaTaskSchedulerService$taskToTask$$inlined$safeCreateCompletable$1.subscribe(RxJavaTaskSchedulerService.kt:176)
        at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

```
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
        at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
        at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
        at io.grpc.netty.shaded.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:219)
        at io.grpc.netty.shaded.io.netty.channel.epoll.Native.<clinit>(Native.java:57)
        at io.grpc.netty.shaded.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.grpc.netty.shaded.io.grpc.netty.Utils.isEpollAvailable(Utils.java:261)
        at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:129)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.<clinit>(NettyServerBuilder.java:78)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:39)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:24)
        at io.grpc.ServerBuilder.forPort(ServerBuilder.java:41)
        at brs.api.grpc.api.ApiService.start(ApiService.kt:90)
        at brs.Burst$4.invoke(Burst.kt:134)
        at brs.Burst$4.invoke(Burst.kt:30)
        at brs.services.impl.RxJavaTaskSchedulerService$taskToTask$$inlined$safeCreateCompletable$1.subscribe(RxJavaTaskSchedulerService.kt:176)
        at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
                at java.lang.Runtime.loadLibrary0(Runtime.java:871)
                at java.lang.System.loadLibrary(System.java:1124)
                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
                at java.security.AccessController.doPrivileged(Native Method)
                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
                at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
                ... 28 more
```

```
[FINE] 2020-03-01 17:37:03 org.ehcache.core.EhcacheManager - Could not create serializers for transaction
org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type 'brs.entity.Transaction'
        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.getSerializerClassFor(DefaultSerializationProvider.java:136)
        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.createSerializer(DefaultSerializationProvider.java:98)
        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.createValueSerializer(DefaultSerializationProvider.java:90)
        at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:464)
        at org.ehcache.core.EhcacheManager.createNewEhcache(EhcacheManager.java:342)
        at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:274)
        at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:584)
        at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:75)
        at brs.services.impl.DBCacheServiceImpl.<init>(DBCacheServiceImpl.kt:45)
        at brs.Burst.<init>(Burst.kt:68)
        at brs.Burst$Companion.init(Burst.kt:260)
        at brs.Burst$Companion.init$default(Burst.kt:258)
        at brs.BurstGUI.runBrs(BurstGUI.kt:130)
        at brs.BurstGUI.access$runBrs(BurstGUI.kt:23)
        at brs.BurstGUI$start$1.run(BurstGUI.kt:40)
        at java.lang.Thread.run(Thread.java:748)
```

```
[FINE] 2020-03-01 17:37:03 org.ehcache.core.EhcacheManager - Could not create serializers for block_id
org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type 'brs.entity.Block'
```

```
[FINE] 2020-03-01 17:37:03 org.ehcache.core.EhcacheManager - Could not create serializers for account
org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type 'brs.entity.Account'
```

```
[FINE] 2020-03-01 17:37:03 org.ehcache.core.EhcacheManager - Could not create serializers for account
org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type 'brs.db.BurstKey'
```

```
[FINE] 2020-03-01 17:37:03 org.ehcache.core.EhcacheManager - Could not create serializers for block_height
org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type 'brs.entity.Block'
```

Strange path of library imho: Found library 'shabal' at /home/lybin/.cache/JNA/temp/jna3820040489095522471.tmp
```
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Looking in classpath from {0} for {1}
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Found library resource at {0}
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Extracting library to {0}
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Trying {0}
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Found jnidispatch at {0}
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Looking for library 'shabal'
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Adding paths from jna.library.path: null
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Trying libshabal.so
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Loading failed with message: libshabal.so: cannot open shared object file: No such file or directory
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /usr/lib/openmpi, /usr/lib/libfakeroot]
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Trying libshabal.so
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Loading failed with message: libshabal.so: cannot open shared object file: No such file or directory
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Looking for version variants
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Looking in classpath from {0} for {1}
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Found library resource at {0}
[FINE] 2020-03-01 17:37:03 com.sun.jna.Native - Extracting library to {0}
[FINE] 2020-03-01 17:37:03 com.sun.jna.NativeLibrary - Found library 'shabal' at /home/lybin/.cache/JNA/temp/jna3820040489095522471.tmp
```

**Comment by harry1453** [comment]
With regard to strange library path...

https://github.com/java-native-access/jna/blob/master/www/GettingStarted.md

```
Make your native library available on your classpath, under the path {OS}-{ARCH}/{LIBRARY}, where {OS}-{ARCH} is JNA's canonical prefix for native libraries (e.g. win32-x86, linux-amd64, or darwin). If the resource is within a jar file it will be automatically extracted when loaded
```

As for the other errors, they come from ehcache and grpc and are logging outputs, I really don't think they are anything to worry about. As they are only logged at the fine / debug level and are not passed down to the program in any way, I think we can consider them internal and handled by the library.
