### ISSUE TITLE
stuck transaction at 754384 

### ISSUE THREAD

**Issue by castorinop** [burst-apps-team/burstcoin#449]
```
burstcoin_1  | [FINE] 2020-09-04 01:21:27 brs.util.DownloadCacheImpl - Cache set to ChainData
burstcoin_1  | [FINE] 2020-09-04 01:21:27 brs.util.DownloadCacheImpl - Cache LastId: 8887113899970181518
burstcoin_1  | [FINE] 2020-09-04 01:21:27 brs.util.DownloadCacheImpl - Cache lastHeight: 754383
burstcoin_1  | [FINE] 2020-09-04 01:21:27 brs.BlockchainProcessorImpl - Generate block failed: Generation signature verification failed for block 754384
burstcoin_1  | [FINE] 2020-09-04 01:21:27 brs.GeneratorImpl - Error in block generation thread
burstcoin_1  | brs.BlockchainProcessor$BlockNotAcceptedException: Generation signature verification failed for block 754384
burstcoin_1  | 	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:831)
burstcoin_1  | 	at brs.BlockchainProcessorImpl.generateBlock(BlockchainProcessorImpl.java:1268)
burstcoin_1  | 	at brs.GeneratorImpl$GeneratorStateImpl.forge(GeneratorImpl.java:214)
burstcoin_1  | 	at brs.GeneratorImpl$GeneratorStateImpl.access$0(GeneratorImpl.java:209)
burstcoin_1  | 	at brs.GeneratorImpl.lambda$0(GeneratorImpl.java:55)
burstcoin_1  | 	at brs.util.ThreadPool.lambda$0(ThreadPool.java:104)
burstcoin_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
burstcoin_1  | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
burstcoin_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
burstcoin_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
burstcoin_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
burstcoin_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
burstcoin_1  | 	at java.lang.Thread.run(Thread.java:748)
burstcoin_1  | [FINE] 2020-09-04 01:21:34 com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=30, active=0, idle=30, waiting=0)
```

**Comment by jjos2372** [comment]
Please try the latest release https://github.com/burst-apps-team/burstcoin/releases/tag/v2.5.4, you database might be inconsistent. In that case you need to sync from scratch. Please re-open if you still have problems after a new sync.
