### ISSUE TITLE
brs quit unexpectedly ! exit code 1

### ISSUE THREAD

**Issue by usengel** [burst-apps-team/burstcoin#496]
![Adsız](https://user-images.githubusercontent.com/85193032/120377277-98d16c80-c325-11eb-9cae-210a6644503f.png)

help

**Comment by jjos2372** [comment]
Hello, thanks for reporting. If possible also include the text logs (shown behind). A common cause for this problem is if you already have another instance running (check the system tray for the Burst icon there).

**Comment by usengel** [comment]
> Hello, thanks for reporting. If possible also include the text logs (shown behind). A common cause for this problem is if you already have another instance running (check the system tray for the Burst icon there).

thank you for the answer. I'm curious about your opinions

`Haz 01, 2021 10:24:27 PM brs.Burst loadProperties
INFO: Initializing Burst Reference Software (BRS) version v3.0.1
Haz 01, 2021 10:24:27 PM brs.Burst loadProperties
INFO: Configurations from folder ./conf
Haz 01, 2021 10:24:27 PM brs.Burst loadProperties
INFO: Custom user properties file brs.properties not loaded
Haz 01, 2021 10:24:27 PM brs.util.LoggerConfigurator init
INFO: Custom user logging.properties not loaded
[INFO] 2021-06-01 22:24:27 brs.Burst - DB.Username using default: ><
[INFO] 2021-06-01 22:24:27 brs.Burst - DB.Password using default: ><
[INFO] 2021-06-01 22:24:27 brs.db.sql.Db - Running flyway migration
[INFO] 2021-06-01 22:24:27 brs.db.sql.Db - Using SQL Backend with Dialect H2
[INFO] 2021-06-01 22:24:28 brs.Burst - brs.testUnconfirmedTransactions using default: >false<
[INFO] 2021-06-01 22:24:28 brs.Burst - brs.disablePullUnconfirmedTransactionsThread using default: >false<
[INFO] 2021-06-01 22:24:28 brs.BlockchainProcessorImpl - Genesis block already in database
[SEVERE] 2021-06-01 22:24:28 brs.Burst - SQL [select "block"."db_id", "block"."id", "block"."version", "block"."timestamp", "block"."previous_block_id", "block"."total_amount", "block"."total_fee", "block"."payload_length", "block"."generator_public_key", "block"."previous_block_hash", "block"."cumulative_difficulty", "block"."base_target", "block"."next_block_id", "block"."height", "block"."generation_signature", "block"."block_signature", "block"."payload_hash", "block"."generator_id", "block"."nonce", "block"."ats" from "block" order by "block"."db_id" desc limit ?]; General error: "java.lang.IllegalStateException: Reading from nio:C:/Users/1/Desktop/1/burst_db/burst.h2.mv.db failed; file length -1 read length 8192 at 7756787525 [1.4.199/1]"; SQL statement:
select "block"."db_id", "block"."id", "block"."version", "block"."timestamp", "block"."previous_block_id", "block"."total_amount", "block"."total_fee", "block"."payload_length", "block"."generator_public_key", "block"."previous_block_hash", "block"."cumulative_difficulty", "block"."base_target", "block"."next_block_id", "block"."height", "block"."generation_signature", "block"."block_signature", "block"."payload_hash", "block"."generator_id", "block"."nonce", "block"."ats" from "block" order by "block"."db_id" desc limit ? [50000-199]
org.jooq.exception.DataAccessException: SQL [select "block"."db_id", "block"."id", "block"."version", "block"."timestamp", "block"."previous_block_id", "block"."total_amount", "block"."total_fee", "block"."payload_length", "block"."generator_public_key", "block"."previous_block_hash", "block"."cumulative_difficulty", "block"."base_target", "block"."next_block_id", "block"."height", "block"."generation_signature", "block"."block_signature", "block"."payload_hash", "block"."generator_id", "block"."nonce", "block"."ats" from "block" order by "block"."db_id" desc limit ?]; General error: "java.lang.IllegalStateException: Reading from nio:C:/Users/1/Desktop/1/burst_db/burst.h2.mv.db failed; file length -1 read length 8192 at 7756787525 [1.4.199/1]"; SQL statement:
select "block"."db_id", "block"."id", "block"."version", "block"."timestamp", "block"."previous_block_id", "block"."total_amount", "block"."total_fee", "block"."payload_length", "block"."generator_public_key", "block"."previous_block_hash", "block"."cumulative_difficulty", "block"."base_target", "block"."next_block_id", "block"."height", "block"."generation_signature", "block"."block_signature", "block"."payload_hash", "block"."generator_id", "block"."nonce", "block"."ats" from "block" order by "block"."db_id" desc limit ? [50000-199]
	at org.jooq_3.14.8.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2903)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:481)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:450)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:464)
	at org.jooq.impl.AbstractResultQuery.fetchAny(AbstractResultQuery.java:930)
	at org.jooq.impl.SelectImpl.fetchAny(SelectImpl.java:3346)
	at brs.db.sql.SqlBlockDb.lambda$findLastBlock$4(SqlBlockDb.java:68)
	at brs.db.sql.Db.useDSLContext(Db.java:230)
	at brs.db.sql.SqlBlockDb.findLastBlock(SqlBlockDb.java:66)
	at brs.BlockchainProcessorImpl.addGenesisBlock(BlockchainProcessorImpl.java:847)
	at brs.BlockchainProcessorImpl.<init>(BlockchainProcessorImpl.java:165)
	at brs.Burst.loadWallet(Burst.java:230)
	at brs.Burst.init(Burst.java:167)
	at brs.Burst.main(Burst.java:151)
	at brs.BurstGUI.runBrs(BurstGUI.java:332)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Reading from nio:C:/Users/1/Desktop/1/burst_db/burst.h2.mv.db failed; file length -1 read length 8192 at 7756787525 [1.4.199/1]"; SQL statement:
select "block"."db_id", "block"."id", "block"."version", "block"."timestamp", "block"."previous_block_id", "block"."total_amount", "block"."total_fee", "block"."payload_length", "block"."generator_public_key", "block"."previous_block_hash", "block"."cumulative_difficulty", "block"."base_target", "block"."next_block_id", "block"."height", "block"."generation_signature", "block"."block_signature", "block"."payload_hash", "block"."generator_id", "block"."nonce", "block"."ats" from "block" order by "block"."db_id" desc limit ? [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.command.Command.executeQuery(Command.java:219)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:243)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4201)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	... 15 more
Caused by: java.lang.IllegalStateException: Reading from nio:C:/Users/1/Desktop/1/burst_db/burst.h2.mv.db failed; file length -1 read length 8192 at 7756787525 [1.4.199/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:420)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1048)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
	at org.h2.mvstore.tx.TransactionMap$TMIterator.fetchNext(TransactionMap.java:711)
	at org.h2.mvstore.tx.TransactionMap$TMIterator.next(TransactionMap.java:752)
	at org.h2.mvstore.db.MVPrimaryIndex$MVStoreCursor.next(MVPrimaryIndex.java:474)
	at org.h2.index.IndexCursor.next(IndexCursor.java:291)
	at org.h2.table.TableFilter.next(TableFilter.java:506)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1882)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
	at org.h2.result.LazyResult.next(LazyResult.java:60)
	at org.h2.command.dml.Select.queryFlat(Select.java:742)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:884)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:151)
	at org.h2.command.dml.Query.query(Query.java:435)
	at org.h2.command.dml.Query.query(Query.java:397)
	at org.h2.command.CommandContainer.query(CommandContainer.java:145)
	at org.h2.command.Command.executeQuery(Command.java:202)
	... 22 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(Unknown Source)
	at sun.nio.ch.FileChannelImpl.read(Unknown Source)
	at org.h2.store.fs.FileNio.read(FilePathNio.java:74)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:406)
	... 43 more
[SEVERE] 2021-06-01 22:24:28 brs.BurstGUI - BRS Quit unexpectedly! Exit code  1
Showing message: BRS Quit unexpectedly! Exit code 1
`

**Comment by jjos2372** [comment]
It looks like your database is corrupted. Maybe an unclean shutdown or some similar event. You probably need to delete your db inside the burst_db folder.

**Comment by usengel** [comment]
> Veritabanınız bozulmuş gibi görünüyor. Belki temiz olmayan bir kapanma veya benzer bir olay. Muhtemelen db'nizi burst_db klasörü içinde silmeniz gerekir.

Will my wallet be deleted?  I don't want to lose my burst coins :)

**Comment by jjos2372** [comment]
> 
> Will my wallet be deleted? I don't want to lose my burst coins :)

Your coins are tied to your passphrase and not to the node software you are running. You can also access your coins using for instance https://phoenix-wallet.rocks/

**Comment by jjos2372** [comment]
Closing as the user reported the problem was fixed by restarting the machine. So the database got locked for some reason on Windows.
