### ISSUE TITLE
Issue running jar file

### ISSUE THREAD

**Issue by mattdemarillac** [burst-apps-team/burstcoin#511]
Just running into a problem with running the 3.0 release via Java
Ive downloaded the recommended jre.
Im getting:

```
Jun 25, 2021 12:09:36 PM brs.Burst loadProperties
INFO: Initializing Burst Reference Software (BRS) version v3.0.0
Jun 25, 2021 12:09:36 PM brs.Burst loadProperties
INFO: Configurations from folder ./conf
Jun 25, 2021 12:09:36 PM brs.BurstGUI runBrs
SEVERE: BurstGUI caught exception starting BRS
java.lang.RuntimeException: Error loading brs-default.properties
	at brs.Burst.loadProperties(Burst.java:101)
	at brs.Burst.init(Burst.java:166)
	at brs.Burst.main(Burst.java:150)
	at brs.BurstGUI.runBrs(BurstGUI.java:318)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: ./conf/brs-default.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at brs.Burst.loadProperties(Burst.java:98)
	... 4 more

Showing message: BurstGUI caught exception starting BRS
```

This file is definately there and ive tried changing file permissions.

Thanks.

**Comment by jjos2372** [comment]
How do you run the JAR file? What is the working directory?

**Comment by mattdemarillac** [comment]
@jjos2372 I found the problem, it was because I was using ZSH. Switching to bash it worked perfectly.
Can confirm this made a difference on both OSX and Ubuntu.
Cheers.

**Comment by jjos2372** [comment]
Great, thanks for reporting back.
